/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.demo

import io.github.oshai.kotlinlogging.KotlinLogging

private val logger = KotlinLogging.logger {}

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    logger.info { App().greeting }
}